import { request } from "@/utils/request";

export async function getBookList(data) {
    // const url = '/api/book/list'
    // const res = await request({ url, method: 'get', data }).catch(err => {
    //     return Promise.reject(res)
    // })
    // if (res.code != 200) {
    //     return Promise.reject(res)
    // }
    // return res.data
    let fetchData = {
        "lists": [
            {
                "id": 1,
                "userId": 1,
                "title": "人类简史",
                "isbn": 9910216477018,
                "publisher": "上海人民出版社",
                "pubdate": "1987-08-12",
                "author": "Anna Anderson",
                "translator": "董强",
                "binding": "精装",
                "price": 88.51,
                "pages": 89,
                "words": 76,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 2.6,
                "review_num": 81,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 2,
                "userId": 2,
                "title": "Thread",
                "isbn": 9794800759929,
                "publisher": "上海人民出版社",
                "pubdate": "2013-07-20",
                "author": "Jose Thomas",
                "translator": "于强",
                "binding": "精装",
                "price": 74.42,
                "pages": 71,
                "words": 70,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 10.5,
                "review_num": 85,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 3,
                "userId": 3,
                "title": "老人与海",
                "isbn": 9884893882343,
                "publisher": "上海人民出版社",
                "pubdate": "1975-05-08",
                "author": "Dorothy Clark",
                "translator": "段勇",
                "binding": "精装",
                "price": 99.61,
                "pages": 90,
                "words": 60,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 9.1,
                "review_num": 93,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 4,
                "userId": 4,
                "title": "冬天的早班飞机",
                "isbn": 9849311004412,
                "publisher": "上海人民出版社",
                "pubdate": "2021-08-02",
                "author": "Richard Brown",
                "translator": "廖霞",
                "binding": "精装",
                "price": 73.14,
                "pages": 88,
                "words": 67,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 9.4,
                "review_num": 92,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 5,
                "userId": 1,
                "title": "在路上",
                "isbn": 9881935810827,
                "publisher": "上海人民出版社",
                "pubdate": "1983-05-14",
                "author": "Dorothy Clark",
                "translator": "谢刚",
                "binding": "精装",
                "price": 99.94,
                "pages": 75,
                "words": 85,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 3.7,
                "review_num": 63,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 6,
                "userId": 2,
                "title": "给樱桃以性别",
                "isbn": 9965501025525,
                "publisher": "上海人民出版社",
                "pubdate": "2008-08-30",
                "author": "[法]圣-埃克苏佩里",
                "translator": "万明",
                "binding": "精装",
                "price": 68.86,
                "pages": 96,
                "words": 81,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 8.4,
                "review_num": 78,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 7,
                "userId": 3,
                "title": "Cat in the Underworld",
                "isbn": 9868656929372,
                "publisher": "上海人民出版社",
                "pubdate": "1993-07-30",
                "author": "Deborah Martinez",
                "translator": "姜丽",
                "binding": "精装",
                "price": 71.34,
                "pages": 89,
                "words": 77,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 8.1,
                "review_num": 68,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 8,
                "userId": 4,
                "title": "Rakehell's Fog",
                "isbn": 9846192271113,
                "publisher": "上海人民出版社",
                "pubdate": "1979-06-28",
                "author": "[英]毛姆",
                "translator": "林秀英",
                "binding": "精装",
                "price": 68.45,
                "pages": 71,
                "words": 69,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 7.6,
                "review_num": 81,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 9,
                "userId": 1,
                "title": "Triumph of the Empire",
                "isbn": 9848000124175,
                "publisher": "上海人民出版社",
                "pubdate": "2016-09-08",
                "author": "Jessica Young",
                "translator": "邓强",
                "binding": "精装",
                "price": 75.54,
                "pages": 74,
                "words": 79,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 6.2,
                "review_num": 91,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 10,
                "userId": 2,
                "title": "我们始终没有牵手旅行",
                "isbn": 9832749211739,
                "publisher": "上海人民出版社",
                "pubdate": "2019-04-26",
                "author": "[哥]加西亚·马尔克斯",
                "translator": "雷洋",
                "binding": "精装",
                "price": 76.05,
                "pages": 70,
                "words": 69,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 4.7,
                "review_num": 63,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 11,
                "userId": 3,
                "title": "绿皮书",
                "isbn": 9972788911019,
                "publisher": "上海人民出版社",
                "pubdate": "2001-08-16",
                "author": "Donald Hernandez",
                "translator": "黄磊",
                "binding": "精装",
                "price": 83.14,
                "pages": 78,
                "words": 76,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 4.4,
                "review_num": 100,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 12,
                "userId": 4,
                "title": "一部法国小说",
                "isbn": 9915845881269,
                "publisher": "上海人民出版社",
                "pubdate": "1986-05-23",
                "author": "Gary Jones",
                "translator": "方磊",
                "binding": "精装",
                "price": 68.13,
                "pages": 98,
                "words": 73,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 9.2,
                "review_num": 72,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 13,
                "userId": 1,
                "title": "Brother's Rainbow",
                "isbn": 9866707661380,
                "publisher": "上海人民出版社",
                "pubdate": "2007-11-25",
                "author": "Mary Gonzalez",
                "translator": "廖娟",
                "binding": "精装",
                "price": 77.53,
                "pages": 97,
                "words": 61,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 1.5,
                "review_num": 71,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 14,
                "userId": 2,
                "title": "地下时光",
                "isbn": 9917207275393,
                "publisher": "上海人民出版社",
                "pubdate": "1992-04-10",
                "author": "Anna Anderson",
                "translator": "李刚",
                "binding": "精装",
                "price": 65.62,
                "pages": 80,
                "words": 84,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 7.1,
                "review_num": 92,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 15,
                "userId": 3,
                "title": "追风筝的人",
                "isbn": 9844168719779,
                "publisher": "上海人民出版社",
                "pubdate": "2006-09-21",
                "author": "Jose Thomas",
                "translator": "易霞",
                "binding": "精装",
                "price": 96.72,
                "pages": 61,
                "words": 77,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 8.4,
                "review_num": 82,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 16,
                "userId": 4,
                "title": "Church in the Glass",
                "isbn": 9897058681713,
                "publisher": "上海人民出版社",
                "pubdate": "2012-03-17",
                "author": "Dorothy Clark",
                "translator": "邹娟",
                "binding": "精装",
                "price": 92.67,
                "pages": 83,
                "words": 68,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 5.6,
                "review_num": 72,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 17,
                "userId": 1,
                "title": "A Marriage Collection",
                "isbn": 9936578703349,
                "publisher": "上海人民出版社",
                "pubdate": "2011-11-12",
                "author": "Richard Brown",
                "translator": "贾磊",
                "binding": "精装",
                "price": 82.18,
                "pages": 87,
                "words": 74,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 4.3,
                "review_num": 80,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 18,
                "userId": 2,
                "title": "天使与昆虫",
                "isbn": 9838014444777,
                "publisher": "上海人民出版社",
                "pubdate": "2010-05-18",
                "author": "Dorothy Clark",
                "translator": "顾秀兰",
                "binding": "精装",
                "price": 92.23,
                "pages": 70,
                "words": 99,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 2.7,
                "review_num": 67,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 19,
                "userId": 3,
                "title": "最后的仪式",
                "isbn": 9887314604611,
                "publisher": "上海人民出版社",
                "pubdate": "2016-12-18",
                "author": "[法]圣-埃克苏佩里",
                "translator": "马超",
                "binding": "精装",
                "price": 79.43,
                "pages": 89,
                "words": 76,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 7.9,
                "review_num": 76,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 20,
                "userId": 4,
                "title": "十一种孤独",
                "isbn": 9830482233489,
                "publisher": "上海人民出版社",
                "pubdate": "2000-11-15",
                "author": "Deborah Martinez",
                "translator": "赵芳",
                "binding": "精装",
                "price": 62.87,
                "pages": 74,
                "words": 80,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 1.4,
                "review_num": 77,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 21,
                "userId": 1,
                "title": "The Time of War",
                "isbn": 9953311700615,
                "publisher": "上海人民出版社",
                "pubdate": "1984-09-29",
                "author": "[英]毛姆",
                "translator": "范刚",
                "binding": "精装",
                "price": 85.62,
                "pages": 97,
                "words": 85,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 5.6,
                "review_num": 83,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 22,
                "userId": 2,
                "title": "Destiny's Cut",
                "isbn": 9878873519296,
                "publisher": "上海人民出版社",
                "pubdate": "1992-06-09",
                "author": "Jessica Young",
                "translator": "谢丽",
                "binding": "精装",
                "price": 66.87,
                "pages": 63,
                "words": 66,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 2.8,
                "review_num": 85,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 23,
                "userId": 3,
                "title": "最初的爱情",
                "isbn": 9907277627139,
                "publisher": "上海人民出版社",
                "pubdate": "1992-09-04",
                "author": "[哥]加西亚·马尔克斯",
                "translator": "林敏",
                "binding": "精装",
                "price": 89.01,
                "pages": 98,
                "words": 91,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 7.8,
                "review_num": 73,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 24,
                "userId": 4,
                "title": "The Thug Chaser",
                "isbn": 9786247286595,
                "publisher": "上海人民出版社",
                "pubdate": "1982-11-18",
                "author": "Donald Hernandez",
                "translator": "董军",
                "binding": "精装",
                "price": 100.21,
                "pages": 84,
                "words": 93,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 8.9,
                "review_num": 79,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 25,
                "userId": 1,
                "title": "小王子",
                "isbn": 9915825629698,
                "publisher": "上海人民出版社",
                "pubdate": "2008-06-07",
                "author": "Gary Jones",
                "translator": "白娟",
                "binding": "精装",
                "price": 61.24,
                "pages": 67,
                "words": 83,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 5.1,
                "review_num": 92,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 26,
                "userId": 2,
                "title": "还乡之谜",
                "isbn": 9966838980708,
                "publisher": "上海人民出版社",
                "pubdate": "1987-07-02",
                "author": "Mary Gonzalez",
                "translator": "熊芳",
                "binding": "精装",
                "price": 69.65,
                "pages": 98,
                "words": 73,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 5.4,
                "review_num": 66,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 27,
                "userId": 3,
                "title": "心有林夕",
                "isbn": 9947979510481,
                "publisher": "上海人民出版社",
                "pubdate": "1970-11-25",
                "author": "Anna Anderson",
                "translator": "袁洋",
                "binding": "精装",
                "price": 84.58,
                "pages": 69,
                "words": 75,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 5.1,
                "review_num": 94,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 28,
                "userId": 4,
                "title": "不想告别的夏天",
                "isbn": 9935280846194,
                "publisher": "上海人民出版社",
                "pubdate": "1998-06-05",
                "author": "Jose Thomas",
                "translator": "余刚",
                "binding": "精装",
                "price": 84.93,
                "pages": 73,
                "words": 68,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 1.7,
                "review_num": 67,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 29,
                "userId": 1,
                "title": "Destiny's Hero",
                "isbn": 9930855346996,
                "publisher": "上海人民出版社",
                "pubdate": "1998-02-01",
                "author": "Dorothy Clark",
                "translator": "林敏",
                "binding": "精装",
                "price": 99.72,
                "pages": 76,
                "words": 96,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 10.5,
                "review_num": 98,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 30,
                "userId": 2,
                "title": "麦田里的守望者",
                "isbn": 9869948218688,
                "publisher": "上海人民出版社",
                "pubdate": "2000-12-20",
                "author": "Richard Brown",
                "translator": "尹娟",
                "binding": "精装",
                "price": 95.33,
                "pages": 78,
                "words": 67,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 9.6,
                "review_num": 85,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 31,
                "userId": 3,
                "title": "Midwife and Light",
                "isbn": 9965903299170,
                "publisher": "上海人民出版社",
                "pubdate": "2019-04-30",
                "author": "Dorothy Clark",
                "translator": "金涛",
                "binding": "精装",
                "price": 91.52,
                "pages": 90,
                "words": 70,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 2.5,
                "review_num": 81,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 32,
                "userId": 4,
                "title": "百年孤独",
                "isbn": 9852258361608,
                "publisher": "上海人民出版社",
                "pubdate": "1992-01-28",
                "author": "[法]圣-埃克苏佩里",
                "translator": "袁洋",
                "binding": "精装",
                "price": 75.33,
                "pages": 95,
                "words": 77,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 1.3,
                "review_num": 95,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 33,
                "userId": 1,
                "title": "Sapphire Raiders",
                "isbn": 9903882243235,
                "publisher": "上海人民出版社",
                "pubdate": "2020-03-26",
                "author": "Deborah Martinez",
                "translator": "范秀英",
                "binding": "精装",
                "price": 91.37,
                "pages": 76,
                "words": 87,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 4.2,
                "review_num": 79,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 34,
                "userId": 2,
                "title": "A Dream of Justice",
                "isbn": 9915149566527,
                "publisher": "上海人民出版社",
                "pubdate": "2015-12-10",
                "author": "[英]毛姆",
                "translator": "宋磊",
                "binding": "精装",
                "price": 87.65,
                "pages": 79,
                "words": 74,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 6.5,
                "review_num": 77,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 35,
                "userId": 3,
                "title": "The Ragged ",
                "isbn": 9931809728313,
                "publisher": "上海人民出版社",
                "pubdate": "1985-01-01",
                "author": "Jessica Young",
                "translator": "谭超",
                "binding": "精装",
                "price": 90.37,
                "pages": 89,
                "words": 63,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 2.5,
                "review_num": 86,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 36,
                "userId": 4,
                "title": "时间简史",
                "isbn": 9815764854793,
                "publisher": "上海人民出版社",
                "pubdate": "2006-02-23",
                "author": "[哥]加西亚·马尔克斯",
                "translator": "冯磊",
                "binding": "精装",
                "price": 66.74,
                "pages": 65,
                "words": 91,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 9.2,
                "review_num": 90,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 37,
                "userId": 1,
                "title": "The Trophy Failure",
                "isbn": 9796564599267,
                "publisher": "上海人民出版社",
                "pubdate": "2022-02-20",
                "author": "Donald Hernandez",
                "translator": "潘伟",
                "binding": "精装",
                "price": 68.92,
                "pages": 68,
                "words": 88,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 8.2,
                "review_num": 68,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 38,
                "userId": 2,
                "title": "人类简史",
                "isbn": 9836843997486,
                "publisher": "上海人民出版社",
                "pubdate": "1999-07-06",
                "author": "Gary Jones",
                "translator": "廖涛",
                "binding": "精装",
                "price": 83.17,
                "pages": 63,
                "words": 66,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 7.8,
                "review_num": 98,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 39,
                "userId": 3,
                "title": "Thread",
                "isbn": 9947290893959,
                "publisher": "上海人民出版社",
                "pubdate": "2012-07-24",
                "author": "Mary Gonzalez",
                "translator": "叶敏",
                "binding": "精装",
                "price": 82.38,
                "pages": 76,
                "words": 85,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 0.4,
                "review_num": 71,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 40,
                "userId": 4,
                "title": "老人与海",
                "isbn": 9865860542393,
                "publisher": "上海人民出版社",
                "pubdate": "1976-09-24",
                "author": "Anna Anderson",
                "translator": "夏艳",
                "binding": "精装",
                "price": 97.07,
                "pages": 62,
                "words": 61,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 9.6,
                "review_num": 93,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 41,
                "userId": 1,
                "title": "冬天的早班飞机",
                "isbn": 9967941153694,
                "publisher": "上海人民出版社",
                "pubdate": "1979-07-06",
                "author": "Jose Thomas",
                "translator": "冯艳",
                "binding": "精装",
                "price": 87.33,
                "pages": 86,
                "words": 80,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 5.5,
                "review_num": 88,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 42,
                "userId": 2,
                "title": "在路上",
                "isbn": 9910916626015,
                "publisher": "上海人民出版社",
                "pubdate": "1999-04-01",
                "author": "Dorothy Clark",
                "translator": "贺勇",
                "binding": "精装",
                "price": 84.79,
                "pages": 68,
                "words": 66,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 3.7,
                "review_num": 61,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 43,
                "userId": 3,
                "title": "给樱桃以性别",
                "isbn": 9877478066005,
                "publisher": "上海人民出版社",
                "pubdate": "2016-05-12",
                "author": "Richard Brown",
                "translator": "江丽",
                "binding": "精装",
                "price": 90.33,
                "pages": 95,
                "words": 74,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 1.2,
                "review_num": 66,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 44,
                "userId": 4,
                "title": "Cat in the Underworld",
                "isbn": 9892513082646,
                "publisher": "上海人民出版社",
                "pubdate": "1983-12-21",
                "author": "Dorothy Clark",
                "translator": "林明",
                "binding": "精装",
                "price": 96.56,
                "pages": 93,
                "words": 91,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 6.3,
                "review_num": 90,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 45,
                "userId": 1,
                "title": "Rakehell's Fog",
                "isbn": 9840266074327,
                "publisher": "上海人民出版社",
                "pubdate": "1971-02-09",
                "author": "[法]圣-埃克苏佩里",
                "translator": "杜强",
                "binding": "精装",
                "price": 64.72,
                "pages": 60,
                "words": 87,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 5.1,
                "review_num": 79,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 46,
                "userId": 2,
                "title": "Triumph of the Empire",
                "isbn": 9809659223631,
                "publisher": "上海人民出版社",
                "pubdate": "1989-01-16",
                "author": "Deborah Martinez",
                "translator": "龙丽",
                "binding": "精装",
                "price": 84.83,
                "pages": 89,
                "words": 76,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 2.2,
                "review_num": 99,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 47,
                "userId": 3,
                "title": "我们始终没有牵手旅行",
                "isbn": 9871828018245,
                "publisher": "上海人民出版社",
                "pubdate": "1990-02-20",
                "author": "[英]毛姆",
                "translator": "郑杰",
                "binding": "精装",
                "price": 93.99,
                "pages": 76,
                "words": 71,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 9.8,
                "review_num": 92,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 48,
                "userId": 4,
                "title": "绿皮书",
                "isbn": 9925871122722,
                "publisher": "上海人民出版社",
                "pubdate": "1982-03-22",
                "author": "Jessica Young",
                "translator": "卢娟",
                "binding": "精装",
                "price": 80.35,
                "pages": 86,
                "words": 61,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 4.9,
                "review_num": 84,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 49,
                "userId": 1,
                "title": "一部法国小说",
                "isbn": 9817367223002,
                "publisher": "上海人民出版社",
                "pubdate": "2019-06-10",
                "author": "[哥]加西亚·马尔克斯",
                "translator": "雷勇",
                "binding": "精装",
                "price": 78.11,
                "pages": 80,
                "words": 88,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 2.3,
                "review_num": 92,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 50,
                "userId": 2,
                "title": "Brother's Rainbow",
                "isbn": 9911665464605,
                "publisher": "上海人民出版社",
                "pubdate": "1990-09-06",
                "author": "Donald Hernandez",
                "translator": "锺杰",
                "binding": "精装",
                "price": 99.87,
                "pages": 99,
                "words": 67,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 7.4,
                "review_num": 86,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 51,
                "userId": 3,
                "title": "地下时光",
                "isbn": 9980431988062,
                "publisher": "上海人民出版社",
                "pubdate": "2017-01-12",
                "author": "Gary Jones",
                "translator": "万勇",
                "binding": "精装",
                "price": 91.28,
                "pages": 68,
                "words": 71,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 9.7,
                "review_num": 63,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 52,
                "userId": 4,
                "title": "追风筝的人",
                "isbn": 9789769947609,
                "publisher": "上海人民出版社",
                "pubdate": "2003-03-02",
                "author": "Mary Gonzalez",
                "translator": "金秀兰",
                "binding": "精装",
                "price": 79.34,
                "pages": 62,
                "words": 88,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 5.7,
                "review_num": 82,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 53,
                "userId": 1,
                "title": "Church in the Glass",
                "isbn": 9914071102171,
                "publisher": "上海人民出版社",
                "pubdate": "1979-10-25",
                "author": "Anna Anderson",
                "translator": "陈霞",
                "binding": "精装",
                "price": 68.34,
                "pages": 85,
                "words": 69,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 6.2,
                "review_num": 72,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 54,
                "userId": 2,
                "title": "A Marriage Collection",
                "isbn": 9923898573199,
                "publisher": "上海人民出版社",
                "pubdate": "1988-07-31",
                "author": "Jose Thomas",
                "translator": "丁涛",
                "binding": "精装",
                "price": 68.35,
                "pages": 93,
                "words": 76,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 6.7,
                "review_num": 74,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 55,
                "userId": 3,
                "title": "天使与昆虫",
                "isbn": 9940243363468,
                "publisher": "上海人民出版社",
                "pubdate": "2003-03-12",
                "author": "Dorothy Clark",
                "translator": "唐芳",
                "binding": "精装",
                "price": 73.35,
                "pages": 65,
                "words": 62,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 1.2,
                "review_num": 73,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 56,
                "userId": 4,
                "title": "最后的仪式",
                "isbn": 9923787442669,
                "publisher": "上海人民出版社",
                "pubdate": "2019-02-22",
                "author": "Richard Brown",
                "translator": "赖强",
                "binding": "精装",
                "price": 86.48,
                "pages": 74,
                "words": 80,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 5.5,
                "review_num": 97,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 57,
                "userId": 1,
                "title": "十一种孤独",
                "isbn": 9920854966969,
                "publisher": "上海人民出版社",
                "pubdate": "2007-05-13",
                "author": "Dorothy Clark",
                "translator": "江霞",
                "binding": "精装",
                "price": 78.16,
                "pages": 80,
                "words": 83,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 8.6,
                "review_num": 76,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 58,
                "userId": 2,
                "title": "The Time of War",
                "isbn": 9805226679155,
                "publisher": "上海人民出版社",
                "pubdate": "2000-05-12",
                "author": "[法]圣-埃克苏佩里",
                "translator": "常娟",
                "binding": "精装",
                "price": 66.57,
                "pages": 78,
                "words": 73,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 10.3,
                "review_num": 60,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 59,
                "userId": 3,
                "title": "Destiny's Cut",
                "isbn": 9873041299925,
                "publisher": "上海人民出版社",
                "pubdate": "1971-07-15",
                "author": "Deborah Martinez",
                "translator": "郭强",
                "binding": "精装",
                "price": 64.95,
                "pages": 79,
                "words": 67,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 7.9,
                "review_num": 94,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 60,
                "userId": 4,
                "title": "最初的爱情",
                "isbn": 9793007208366,
                "publisher": "上海人民出版社",
                "pubdate": "2004-09-08",
                "author": "[英]毛姆",
                "translator": "魏静",
                "binding": "精装",
                "price": 63.39,
                "pages": 72,
                "words": 86,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 4.5,
                "review_num": 75,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 61,
                "userId": 1,
                "title": "The Thug Chaser",
                "isbn": 9842826085957,
                "publisher": "上海人民出版社",
                "pubdate": "1993-08-28",
                "author": "Jessica Young",
                "translator": "汤刚",
                "binding": "精装",
                "price": 95.38,
                "pages": 83,
                "words": 66,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 2.5,
                "review_num": 66,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 62,
                "userId": 2,
                "title": "小王子",
                "isbn": 9834210462423,
                "publisher": "上海人民出版社",
                "pubdate": "1998-09-11",
                "author": "[哥]加西亚·马尔克斯",
                "translator": "叶磊",
                "binding": "精装",
                "price": 96.53,
                "pages": 75,
                "words": 83,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 6.2,
                "review_num": 99,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 63,
                "userId": 3,
                "title": "还乡之谜",
                "isbn": 9843050204754,
                "publisher": "上海人民出版社",
                "pubdate": "1991-10-26",
                "author": "Donald Hernandez",
                "translator": "曹杰",
                "binding": "精装",
                "price": 78.75,
                "pages": 62,
                "words": 94,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 10.4,
                "review_num": 76,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 64,
                "userId": 4,
                "title": "心有林夕",
                "isbn": 9795510960962,
                "publisher": "上海人民出版社",
                "pubdate": "1998-05-11",
                "author": "Gary Jones",
                "translator": "金军",
                "binding": "精装",
                "price": 67.25,
                "pages": 85,
                "words": 99,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 4.5,
                "review_num": 81,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 65,
                "userId": 1,
                "title": "不想告别的夏天",
                "isbn": 9816071312688,
                "publisher": "上海人民出版社",
                "pubdate": "1989-12-17",
                "author": "Mary Gonzalez",
                "translator": "邓娜",
                "binding": "精装",
                "price": 80.63,
                "pages": 84,
                "words": 95,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 9.6,
                "review_num": 76,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 66,
                "userId": 2,
                "title": "Destiny's Hero",
                "isbn": 9829041735416,
                "publisher": "上海人民出版社",
                "pubdate": "2003-11-21",
                "author": "Anna Anderson",
                "translator": "曹强",
                "binding": "精装",
                "price": 99.83,
                "pages": 86,
                "words": 98,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 3.2,
                "review_num": 96,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 67,
                "userId": 3,
                "title": "麦田里的守望者",
                "isbn": 9785799332998,
                "publisher": "上海人民出版社",
                "pubdate": "1996-01-22",
                "author": "Jose Thomas",
                "translator": "夏刚",
                "binding": "精装",
                "price": 67.14,
                "pages": 67,
                "words": 82,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 2.8,
                "review_num": 81,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 68,
                "userId": 4,
                "title": "Midwife and Light",
                "isbn": 9947241220151,
                "publisher": "上海人民出版社",
                "pubdate": "1993-04-19",
                "author": "Dorothy Clark",
                "translator": "石艳",
                "binding": "精装",
                "price": 84.79,
                "pages": 93,
                "words": 71,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 7.5,
                "review_num": 65,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 69,
                "userId": 1,
                "title": "百年孤独",
                "isbn": 9820479308309,
                "publisher": "上海人民出版社",
                "pubdate": "2007-04-28",
                "author": "Richard Brown",
                "translator": "孟磊",
                "binding": "精装",
                "price": 82.24,
                "pages": 65,
                "words": 95,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 5.3,
                "review_num": 65,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 70,
                "userId": 2,
                "title": "Sapphire Raiders",
                "isbn": 9937365048913,
                "publisher": "上海人民出版社",
                "pubdate": "2021-06-26",
                "author": "Dorothy Clark",
                "translator": "汪军",
                "binding": "精装",
                "price": 66.85,
                "pages": 61,
                "words": 61,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 0.8,
                "review_num": 67,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 71,
                "userId": 3,
                "title": "A Dream of Justice",
                "isbn": 9905258732414,
                "publisher": "上海人民出版社",
                "pubdate": "1995-03-24",
                "author": "[法]圣-埃克苏佩里",
                "translator": "林艳",
                "binding": "精装",
                "price": 99.41,
                "pages": 63,
                "words": 93,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 0.5,
                "review_num": 78,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 72,
                "userId": 4,
                "title": "The Ragged ",
                "isbn": 9963399023571,
                "publisher": "上海人民出版社",
                "pubdate": "1976-02-16",
                "author": "Deborah Martinez",
                "translator": "张明",
                "binding": "精装",
                "price": 67.28,
                "pages": 75,
                "words": 61,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 2.6,
                "review_num": 63,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 73,
                "userId": 1,
                "title": "时间简史",
                "isbn": 9890494157863,
                "publisher": "上海人民出版社",
                "pubdate": "2001-03-07",
                "author": "[英]毛姆",
                "translator": "易洋",
                "binding": "精装",
                "price": 96.89,
                "pages": 84,
                "words": 90,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 3.4,
                "review_num": 92,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 74,
                "userId": 2,
                "title": "The Trophy Failure",
                "isbn": 9975833802111,
                "publisher": "上海人民出版社",
                "pubdate": "1983-09-20",
                "author": "Jessica Young",
                "translator": "魏芳",
                "binding": "精装",
                "price": 96.62,
                "pages": 86,
                "words": 98,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 8.3,
                "review_num": 90,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 75,
                "userId": 3,
                "title": "人类简史",
                "isbn": 9913346052309,
                "publisher": "上海人民出版社",
                "pubdate": "2007-11-10",
                "author": "[哥]加西亚·马尔克斯",
                "translator": "杨秀兰",
                "binding": "精装",
                "price": 86.45,
                "pages": 88,
                "words": 79,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 3.1,
                "review_num": 92,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 76,
                "userId": 4,
                "title": "Thread",
                "isbn": 9831601766073,
                "publisher": "上海人民出版社",
                "pubdate": "2014-12-15",
                "author": "Donald Hernandez",
                "translator": "吴杰",
                "binding": "精装",
                "price": 92.55,
                "pages": 95,
                "words": 88,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 4.4,
                "review_num": 67,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 77,
                "userId": 1,
                "title": "老人与海",
                "isbn": 9967108594270,
                "publisher": "上海人民出版社",
                "pubdate": "1981-02-08",
                "author": "Gary Jones",
                "translator": "薛军",
                "binding": "精装",
                "price": 62.72,
                "pages": 74,
                "words": 65,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 7.4,
                "review_num": 88,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 78,
                "userId": 2,
                "title": "冬天的早班飞机",
                "isbn": 9869592606450,
                "publisher": "上海人民出版社",
                "pubdate": "1984-01-10",
                "author": "Mary Gonzalez",
                "translator": "尹军",
                "binding": "精装",
                "price": 66.13,
                "pages": 65,
                "words": 79,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 4.7,
                "review_num": 89,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 79,
                "userId": 3,
                "title": "在路上",
                "isbn": 9972910581048,
                "publisher": "上海人民出版社",
                "pubdate": "1989-11-18",
                "author": "Anna Anderson",
                "translator": "阎秀英",
                "binding": "精装",
                "price": 98.76,
                "pages": 83,
                "words": 90,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 6.6,
                "review_num": 77,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 80,
                "userId": 4,
                "title": "给樱桃以性别",
                "isbn": 9787258550207,
                "publisher": "上海人民出版社",
                "pubdate": "1987-08-17",
                "author": "Jose Thomas",
                "translator": "田军",
                "binding": "精装",
                "price": 74.51,
                "pages": 81,
                "words": 83,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 8.7,
                "review_num": 97,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 81,
                "userId": 1,
                "title": "Cat in the Underworld",
                "isbn": 9952538762093,
                "publisher": "上海人民出版社",
                "pubdate": "1999-01-10",
                "author": "Dorothy Clark",
                "translator": "周秀兰",
                "binding": "精装",
                "price": 70.44,
                "pages": 98,
                "words": 84,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 4.8,
                "review_num": 75,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 82,
                "userId": 2,
                "title": "Rakehell's Fog",
                "isbn": 9834567423898,
                "publisher": "上海人民出版社",
                "pubdate": "2013-05-30",
                "author": "Richard Brown",
                "translator": "钱艳",
                "binding": "精装",
                "price": 63.98,
                "pages": 88,
                "words": 80,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 1.8,
                "review_num": 100,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 83,
                "userId": 3,
                "title": "Triumph of the Empire",
                "isbn": 9868660906262,
                "publisher": "上海人民出版社",
                "pubdate": "1995-03-24",
                "author": "Dorothy Clark",
                "translator": "许艳",
                "binding": "精装",
                "price": 98.37,
                "pages": 91,
                "words": 91,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 7.8,
                "review_num": 99,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 84,
                "userId": 4,
                "title": "我们始终没有牵手旅行",
                "isbn": 9973859637491,
                "publisher": "上海人民出版社",
                "pubdate": "2002-01-15",
                "author": "[法]圣-埃克苏佩里",
                "translator": "叶杰",
                "binding": "精装",
                "price": 85.13,
                "pages": 96,
                "words": 71,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 1.7,
                "review_num": 98,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 85,
                "userId": 1,
                "title": "绿皮书",
                "isbn": 9924737283324,
                "publisher": "上海人民出版社",
                "pubdate": "1983-08-06",
                "author": "Deborah Martinez",
                "translator": "萧洋",
                "binding": "精装",
                "price": 78.46,
                "pages": 90,
                "words": 66,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 6.4,
                "review_num": 78,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 86,
                "userId": 2,
                "title": "一部法国小说",
                "isbn": 9883895147534,
                "publisher": "上海人民出版社",
                "pubdate": "2009-08-08",
                "author": "[英]毛姆",
                "translator": "曹秀英",
                "binding": "精装",
                "price": 63.86,
                "pages": 73,
                "words": 67,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 4.2,
                "review_num": 61,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            },
            {
                "id": 87,
                "userId": 3,
                "title": "Brother's Rainbow",
                "isbn": 9824324320518,
                "publisher": "上海人民出版社",
                "pubdate": "2010-03-30",
                "author": "Jessica Young",
                "translator": "崔涛",
                "binding": "精装",
                "price": 71.46,
                "pages": 70,
                "words": 99,
                "tags": [
                    "小说",
                    "文学",
                    "名著"
                ],
                "score": 7.9,
                "review_num": 64,
                "image": "https://boom-beiyan-sitemgt.oss-cn-beijing.aliyuncs.com/resource/1649295786624e41aa5a3f1.jpeg",
                "introduction": "12岁的阿富汗富家少爷阿米尔与仆人哈桑情同手足。然而，在一场风筝比赛后，发生了一件悲惨不堪的事，阿米尔为自己的懦弱感到自责和痛苦，逼走了哈桑，不久，自己也跟随父亲逃往美国。\n成年后的阿米尔始终无法原谅自己当年对哈桑的背叛。为了赎罪，阿米尔再度踏上暌违二十多年的故乡，希望能为不幸的好友尽最后一点心力，却发现一个惊天谎言，儿时的噩梦再度重演，阿米尔该如何抉择？\n故事如此残忍而又美丽，作者以温暖细腻的笔法勾勒人性的本质与救赎，读来令人荡气回肠。"
            }
        ],
        "pageInfo": {
            "current": 1,
            "pageSize": 10000,
            "total": 87,
            "maxCurrent": 1
        }
    }
    return fetchData
}
